### ISSUE TITLE
Regional deaths data

### ISSUE THREAD

**Issue by davidhen** [watty62/Scot_covid19#1]
Hi,

The regional deaths csv seems to be incomplete from 18th March onward. Is that a lack of raw data?

Cheers

David

**Comment by watty62** [comment]
Yes - Scots government stopped providing it from day 2 or 3. It was initially possible to piece it together from press reports but they are difficult to find. Happy to take contributions, David.

**Comment by davidhen** [comment]
Thought that might be the case! Thanks for getting back to me. Think it will be a really important piece of info over the coming week/fortnight so will have a trawl and see what we can do. Again, might be back to privacy concerns with small numbers but will see......
